input:
  pdb: null
  pdb_dir: null
  quiver: null

output:
  pdb_dir: null
  quiver: null
  output_intermediates: False

inference:
  num_recycles: 10
  hotspot_show_proportion: 0.1
  cautious: True

model:
  model_weights: /home/weights/RFab_overall_best.pt

model_param:
  n_extra_block: 4
  n_main_block: 36
  d_msa: 256
  d_pair: 128
  d_templ: 64
  n_head_msa: 8
  n_head_pair: 4
  n_head_templ: 4
  d_hidden: 32
  d_hidden_templ: 32
  d_t1d: 23
  p_drop: 0.0
  SE3_param_full:
    num_layers: 1
    num_channels: 48
    num_degrees: 2
    l0_in_features: 32
    l0_out_features: 32
    l1_in_features: 2
    l1_out_features: 2
    num_edge_features: 32
    div: 4
    n_heads: 4
  SE3_param_topk:
    num_layers: 1
    num_channels: 128
    num_degrees: 2
    l0_in_features: 64
    l0_out_features: 64
    l1_in_features: 2
    l1_out_features: 2
    num_edge_features: 64
    div: 4
    n_heads: 4

